# Generated by Django 5.1.6 on 2025-04-30 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='membre',
            fields=[
                ('idmembre', models.AutoField(db_column='idmembre', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='nom', max_length=30)),
                ('prenom', models.CharField(db_column='prenom', max_length=30)),
                ('anneeNais', models.IntegerField(db_column='anneeNais', default=0)),
                ('anneeEntree', models.IntegerField(db_column='anneeEntree', default=0)),
                ('password', models.CharField(db_column='password', max_length=50)),
                ('telephone', models.CharField(db_column='telephone', max_length=15)),
                ('email', models.CharField(db_column='email', max_length=50)),
                ('actif', models.IntegerField(db_column='actif')),
            ],
        ),
        migrations.CreateModel(
            name='epargne',
            fields=[
                ('idEpargne', models.AutoField(db_column='idEpargne', primary_key=True, serialize=False)),
                ('montant', models.DecimalField(db_column='montant', decimal_places=4, max_digits=19)),
                ('modeVersement', models.CharField(db_column='modeVersement', max_length=20)),
                ('couponVersement', models.CharField(db_column='couponVersement', max_length=64)),
                ('dateseance', models.DateField(db_column='idSeance')),
                ('idmembre', models.ForeignKey(db_column='idmembre', on_delete=django.db.models.deletion.CASCADE, to='mon_application.membre')),
            ],
            options={
                'db_table': 'epargne',
            },
        ),
        migrations.CreateModel(
            name='pret',
            fields=[
                ('idpret', models.AutoField(db_column='idpret', primary_key=True, serialize=False)),
                ('datepret', models.DateField(db_column='datepret')),
                ('tauxInteret', models.DecimalField(db_column='tauxInteret', decimal_places=2, max_digits=15)),
                ('montant', models.DecimalField(db_column='montant', decimal_places=2, max_digits=15)),
                ('observations', models.TextField(blank=True, db_column='observations', null=True)),
                ('pourcentage', models.DecimalField(db_column='pourcentage', decimal_places=2, max_digits=15)),
                ('dateseance', models.DateField(db_column='idSeance')),
                ('idmembre', models.ForeignKey(db_column='idmembre', on_delete=django.db.models.deletion.CASCADE, to='mon_application.membre')),
            ],
            options={
                'db_table': 'pret',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'membre',
            },
        ),
        migrations.CreateModel(
            name='remboursement',
            fields=[
                ('idRembo', models.AutoField(db_column='idRembo', primary_key=True, serialize=False)),
                ('dateRembo', models.DateField(db_column='dateRembo')),
                ('montant', models.DecimalField(db_column='montant', decimal_places=2, max_digits=15)),
                ('dateseance', models.DateField(db_column='idseance')),
                ('idpret', models.ForeignKey(db_column='idpret', on_delete=django.db.models.deletion.CASCADE, to='mon_application.pret')),
            ],
            options={
                'db_table': 'remboursement',
            },
        ),
        migrations.CreateModel(
            name='sanction',
            fields=[
                ('idSanction', models.AutoField(db_column='idTontines', primary_key=True, serialize=False)),
                ('dateSanction', models.DateField(db_column='dateSanction')),
                ('typeSanction', models.CharField(db_column='typeTontine', max_length=50)),
                ('montant', models.DecimalField(db_column='montantTontine', decimal_places=2, max_digits=15)),
                ('raison', models.TextField(blank=True, db_column='raison', null=True)),
                ('idmembre', models.ForeignKey(db_column='idmembre', on_delete=django.db.models.deletion.CASCADE, to='mon_application.membre')),
            ],
            options={
                'db_table': 'sanction',
            },
        ),
        migrations.CreateModel(
            name='Tontines',
            fields=[
                ('idTontines', models.AutoField(db_column='idTontines', primary_key=True, serialize=False)),
                ('nomTontines', models.CharField(db_column='nomTontines', max_length=45)),
                ('typeTontine', models.CharField(db_column='typeTontine', max_length=45)),
                ('montantTontine', models.DecimalField(db_column='montantTontine', decimal_places=5, max_digits=20)),
                ('dateCreation', models.DateField(db_column='dateCreation')),
                ('idMembre', models.ForeignKey(db_column='idmembre', on_delete=django.db.models.deletion.CASCADE, to='mon_application.membre')),
            ],
            options={
                'db_table': 'Tontines',
            },
        ),
        migrations.CreateModel(
            name='versementTontine',
            fields=[
                ('idVersTontine', models.AutoField(db_column='idVersCotis', primary_key=True, serialize=False)),
                ('montant', models.DecimalField(db_column='montant', decimal_places=2, max_digits=15)),
                ('modeVersement', models.CharField(db_column='modeVersement', max_length=20)),
                ('couponVersement', models.CharField(db_column='copuonVersement', max_length=64)),
                ('dateseance', models.DateField(db_column='idSeance')),
                ('idTontines', models.ForeignKey(db_column='codeCotisation', on_delete=django.db.models.deletion.CASCADE, to='mon_application.tontines')),
                ('idmembre', models.ForeignKey(db_column='idmembre', on_delete=django.db.models.deletion.CASCADE, to='mon_application.membre')),
            ],
            options={
                'db_table': 'versementTontine',
            },
        ),
    ]
