# Generated by Django 5.1.6 on 2025-04-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('membre', 'Membre')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
