# Generated by Django 5.1.6 on 2025-05-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0003_membre_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='password',
            field=models.CharField(db_column='password', max_length=1000),
        ),
    ]
