# Generated by Django 5.1.6 on 2025-05-18 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0005_alter_membre_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pret',
            name='pourcentage',
        ),
        migrations.RemoveField(
            model_name='tontines',
            name='dateCreation',
        ),
        migrations.RemoveField(
            model_name='tontines',
            name='idMembre',
        ),
        migrations.RemoveField(
            model_name='tontines',
            name='montantTontine',
        ),
        migrations.RemoveField(
            model_name='tontines',
            name='nomTontines',
        ),
        migrations.AddField(
            model_name='pret',
            name='statut',
            field=models.CharField(default='en attente', max_length=20),
        ),
        migrations.AddField(
            model_name='tontines',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='epargne',
            name='dateseance',
            field=models.DateField(db_column='dateseance'),
        ),
        migrations.AlterField(
            model_name='pret',
            name='dateseance',
            field=models.DateField(db_column='dateseance'),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='dateseance',
            field=models.DateField(db_column='dateseance'),
        ),
        migrations.AlterField(
            model_name='tontines',
            name='typeTontine',
            field=models.CharField(choices=[('presence', 'Tontine de Présence'), ('epargne', 'Tontine d_epargne'), ('solidarite', 'Tontine de solidarite'), ('rotative', 'Tontine rotative')], max_length=20),
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_souscription', models.DateTimeField(auto_now_add=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mon_application.membre')),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mon_application.tontines')),
            ],
        ),
        migrations.DeleteModel(
            name='versementTontine',
        ),
    ]
