# Generated by Django 5.1.6 on 2025-05-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0006_remove_pret_pourcentage_remove_tontines_datecreation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='actif',
            field=models.IntegerField(db_column='actif', default=0),
        ),
    ]
