# Generated by Django 5.1.6 on 2025-05-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0007_alter_membre_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='actif',
            field=models.IntegerField(db_column='actif', default=1),
        ),
    ]
