# Generated by Django 5.1.6 on 2025-05-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0008_alter_membre_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pret',
            name='datepret',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pret',
            name='dateseance',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
