# Generated by Django 5.1.6 on 2025-05-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0009_alter_pret_datepret_alter_pret_dateseance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pret',
            name='tauxInteret',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=15),
        ),
    ]
