# Generated by Django 5.1.6 on 2025-05-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0010_alter_pret_tauxinteret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remboursement',
            name='dateseance',
            field=models.DateField(auto_now_add=True),
        ),
    ]
