# Generated by Django 5.1.6 on 2025-05-23 08:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0011_alter_remboursement_dateseance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Don',
            fields=[
                ('idDon', models.AutoField(primary_key=True, serialize=False)),
                ('dateDon', models.DateField(default=django.utils.timezone.now)),
                ('typeDon', models.CharField(choices=[('argent', 'Don en argent'), ('nature', 'Don en nature')], default='argent', max_length=10)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mon_application.membre')),
            ],
        ),
    ]
