# Generated by Django 5.1.6 on 2025-05-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0012_don'),
    ]

    operations = [
    ]
