# Generated by Django 5.1.6 on 2025-05-23 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0013_auto_20250523_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='garant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garant_de', to='mon_application.membre'),
        ),
        migrations.AddField(
            model_name='pret',
            name='garant_cni_image',
            field=models.ImageField(null=True, upload_to='cni_garants/'),
        ),
    ]
